name: C/C++ CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install tools
      run: |
        sudo apt-get update
        sudo apt-get install -qq qt5-default qtmultimedia5-dev
      
    - name: qmake
      run: |
        qmake scplay.pro
        
    - name: make
      run: make
      
