name: C/C++ CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install tools
      run: |
        sudo apt-add-repository -y ppa:beineri/opt-qt521
        sudo apt-get update -qq
        sudo apt-get install -qq qt52-meta-full
        ls -lhR /opt/qt52
        
    - name: qmake
      run: qmake
      
    - name: make
      run: make
      
