name: C/C++ CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install tools
      run: |
        sudo apt-get update
        sudo apt-get install -qq qt5-default qtmultimedia5-dev qtscript5-dev qttools5-dev
      
      
    - name: Setup CodeQL
      uses: github/codeql-action/init@v1
      
    - name: qmake
      run: |
        qmake scplay.pro
        
    - name: make
      run: make
      
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
      with:
        output: ./sarif
      
